import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import worker from '../worker/index.js';
const catalog=JSON.parse(await fs.readFile(new URL('../source/catalog.json',import.meta.url)));
assert.equal(catalog.length,124);assert.equal(new Set(catalog.map(d=>d.id)).size,124);
assert.equal(catalog.filter(d=>d.image).length,30);
assert.equal(catalog.filter(d=>d.category==='Signature Cocktails').length,14);
assert.equal(catalog.find(d=>d.name==='Wepa').category,'Classic Cocktails');
assert.equal(catalog.find(d=>d.name==='Classic Smoked Old Fashioned').category,'Signature Cocktails');
assert(!catalog.some(d=>/BLU LIV|The COV/.test(JSON.stringify(d))));
assert.equal(catalog.find(d=>d.name==='Island Matcha').ingredients.length,4);
assert.match(catalog.find(d=>d.name==='Island Matcha').notes,/0 oz/);
assert.match(catalog.find(d=>d.name==='French 75').notes,/Conflicting glass/);
assert(!catalog.find(d=>d.name==='Ropa Vieja').image);
assert(catalog.find(d=>d.name==='Jerk Chicken').image);
const req=(path,body)=>new Request('https://test.example'+path,body?{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://test.example'},body:JSON.stringify(body)}:{});
assert.equal((await worker.fetch(req('/'),{})).status,200);
assert.equal((await worker.fetch(req('/api/status'),{}).then(r=>r.json())).connected,false);
for(const d of catalog.filter(d=>d.image)){const r=await worker.fetch(req(d.image),{});assert.equal(r.status,200);assert.match(r.headers.get('Content-Type'),/image\/jpeg/);assert((await r.arrayBuffer()).byteLength>1000)}
const lookup=await worker.fetch(req('/api/jari',{message:'What goes in the seafood paella?',mode:'qa'}),{}).then(r=>r.json());assert.equal(lookup.provider,'source-lookup');assert.match(lookup.reply,/Saffron rice/);assert.match(lookup.reply,/PDF page 11/);
const mock=await worker.fetch(req('/api/jari',{message:'Hi',mode:'mock'}),{}).then(r=>r.json());assert.match(mock.reply,/not connected/);
assert.equal((await worker.fetch(new Request('https://test.example/api/jari',{method:'POST',body:'bad'}),{})).status,400);
assert.equal((await worker.fetch(new Request('https://test.example/api/jari',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'}),{})).status,403);
const originalFetch=globalThis.fetch;let outbound;
globalThis.fetch=async(url,opts)=>{outbound=JSON.parse(opts.body);assert.equal(opts.headers.Authorization,'Bearer test-only');return new Response(JSON.stringify({choices:[{message:{content:'The house recipe includes saffron rice.'},finish_reason:'stop'}]}),{headers:{'Content-Type':'application/json'}})};
const ai=await worker.fetch(req('/api/jari',{message:'Seafood paella',mode:'qa'}),{OPENAI_API_KEY:'test-only'}).then(r=>r.json());assert.equal(ai.provider,'openai');assert.match(ai.reply,/saffron/);assert.match(outbound.messages[0].content,/Don Coqui/);assert(!/BLU LIV|The COV/.test(outbound.messages[0].content));globalThis.fetch=originalFetch;
// DOM/state harness checks study and game flows; it is not browser or visual QA.
const nodes=new Map();function node(key){if(!nodes.has(key))nodes.set(key,{innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},attrs:{},listeners:{},classList:{add(){},remove(){},toggle(){return false},contains(){return false}},setAttribute(k,v){this.attrs[k]=v},removeAttribute(k){delete this.attrs[k]},addEventListener(k,fn){this.listeners[k]=fn},scrollIntoView(){},focus(){},showModal(){this.open=true},close(){this.open=false}});return nodes.get(key)}
const tools=[];const document={querySelector:node,querySelectorAll:()=>[],addEventListener(){},modelContext:{registerTool(t){tools.push(t)}}};
const context=vm.createContext({document,window:{scrollTo(){},addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},history:{replaceState(){}},location:{hash:''},fetch:async()=>new Response(JSON.stringify(catalog)),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},AbortController,console,Math,DATA:catalog});
let code=await fs.readFile(new URL('../source/app.js',import.meta.url),'utf8');code=code.replace("const DATA=await fetch('/catalog.json').then(r=>r.json());",'');vm.runInContext(code,context);
assert.match(node('#main').innerHTML,/Know every detail/);
vm.runInContext("navigate('cocktail'); state.game.selected=[...state.game.answers]; lockGame();",context);assert.match(node('#main').innerHTML,/Perfect build/);assert.equal(vm.runInContext('state.game.target.category',context),'Signature Cocktails');assert.equal(vm.runInContext("eligible('drink').length",context),14);assert.equal(vm.runInContext('state.game.score',context),100);
vm.runInContext("setupGame(); state.game.selected=[]; lockGame();",context);assert.equal(vm.runInContext('state.game.lives',context),2);
vm.runInContext("navigate('kitchen'); state.game.time=23; stopTimer(); renderGame();",context);assert.match(node('#main').innerHTML,/clock is paused/);assert.equal(vm.runInContext('state.game.time',context),23);
vm.runInContext("state.flashKind='drink';state.flashCategory='Signature Cocktails';createDeck();navigate('flashcards'); state.flipped=true; renderFlash();",context);assert.match(node('#main').innerHTML,/THE ANSWER/);
const search=tools.find(t=>t.name==='search_don_coqui_menu');assert(search);const found=search.execute({query:'paella',kind:'food'});assert.equal(found.length,1);assert.match(node('#main').innerHTML,/Seafood Paella/);assert.throws(()=>search.execute({query:'paella',kind:'invalid'}));
const flash=tools.find(t=>t.name==='start_don_coqui_flashcards');assert.equal(flash.execute({kind:'drink'}).cards,14);assert.match(node('#main').innerHTML,/Make it second nature/);assert.throws(()=>flash.execute({kind:'invalid'}));
vm.runInContext("state.kind='food';state.category='Starters';state.query='French';navigate('menu');showSuggestions();",context);
assert.match(node('#search-suggestions').innerHTML,/French Kiss/);assert.match(node('#search-suggestions').innerHTML,/French Martini/);assert.equal(node('#search').attrs['aria-expanded'],'true');
assert(vm.runInContext("menuMatches().some(d=>d.name==='French Kiss')",context));
vm.runInContext("state.query='senor';showSuggestions();",context);assert.match(node('#search-suggestions').innerHTML,/Señorita/);
vm.runInContext("state.query='churr';renderMenu();showSuggestions();",context);assert.match(node('#search-suggestions').innerHTML,/Churrasco/);assert.match(node('#search-suggestions').innerHTML,/Churros/);
node('#search').listeners.keydown({key:'ArrowDown',preventDefault(){}});assert.equal(node('#search').attrs['aria-activedescendant'],'search-option-0');
node('#search').listeners.keydown({key:'Enter',preventDefault(){}});assert.equal(node('#details').open,true);assert.match(node('#detail-content').innerHTML,/Churrasco/);
vm.runInContext("state.query='zzz-no-item';renderMenu();showSuggestions();",context);assert.equal(node('#search-suggestions').hidden,true);assert.equal(node('#search').attrs['aria-expanded'],'false');assert.equal(vm.runInContext('menuMatches().length',context),0);
vm.runInContext("state.query='';renderMenu();showSuggestions();",context);assert.equal(node('#search-suggestions').hidden,true);
assert.equal(vm.runInContext("titleMatches('shrimp coconut')[0].name",context),'Coconut Shrimp');
// Open-card browsing preserves filtered order, wraps, and ignores vertical/cancelled gestures.
vm.runInContext("state.kind='food';state.category='Starters';state.query='';openCard(filtered()[0].id);",context);
assert.equal(vm.runInContext('cardBrowse.length',context),10);
const first=vm.runInContext('cardBrowse[0].id',context);
const second=vm.runInContext('cardBrowse[1].id',context);
const gesture=(x,y)=>({pointerId:1,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,target:{closest:()=>null}});
node('#details').listeners.pointerdown(gesture(250,150));
node('#details').listeners.pointerup(gesture(100,155));
assert.equal(vm.runInContext('cardBrowse[cardIndex].id',context),second);
node('#details').listeners.pointerdown(gesture(100,150));
node('#details').listeners.pointerup(gesture(250,155));
assert.equal(vm.runInContext('cardBrowse[cardIndex].id',context),first);
node('#details').listeners.pointerdown(gesture(250,150));
node('#details').listeners.pointermove(gesture(230,280));
node('#details').listeners.pointerup(gesture(100,155));
assert.equal(vm.runInContext('cardIndex',context),0);
node('#details').listeners.pointerdown(gesture(250,150));node('#details').listeners.pointercancel();node('#details').listeners.pointerup(gesture(100,155));
assert.equal(vm.runInContext('cardIndex',context),0);
vm.runInContext('moveOpenCard(-1)',context);assert.equal(vm.runInContext('cardIndex',context),9);
vm.runInContext('moveOpenCard(1)',context);assert.equal(vm.runInContext('cardIndex',context),0);
node('#details').listeners.keydown({key:'ArrowRight',target:{closest:()=>null},preventDefault(){}});
assert.equal(vm.runInContext('cardIndex',context),1);
vm.runInContext("state.kind='drink';state.category='Signature Cocktails';state.query='';openCard(filtered()[0].id);moveOpenCard(1)",context);
assert.equal(vm.runInContext('cardBrowse.length',context),14);
assert.equal(vm.runInContext('cardBrowse[cardIndex].kind',context),'drink');
vm.runInContext("state.query='churr';chooseSuggestion(titleMatches('churr')[0].id)",context);
assert(vm.runInContext('cardBrowse.some(d=>d.name===\"Churros\")',context));
vm.runInContext("openCard(DATA[0].id,[DATA[0]]);moveOpenCard(1)",context);
assert.equal(vm.runInContext('cardIndex',context),0);assert.match(node('#detail-content').innerHTML,/Only card in these results/);
console.log('PASS: menu search, games, filtered food/drink card navigation, swipe directions, vertical scrolling, cancellation, wraparound and keyboard controls.');
